#!/bin/bash

# TODO: Currently, this is hardcoded. Ideally, this should be rewritten to be configurable.

function ps1_powerline {
 
	#local USERTYPE="\[\e[48;5;103m\]\[\e[38;5;15m\]\[\e[1m\]"
	#local USERTYPE_END="\[\e[21m\]\[\e[38;5;103m\]\[\e[1m\]\[\e[0m\]\[\e[21m\]"
	#\[\e[1m\]

	local USER="\[\e[0m\]\[\e[38;5;60m\]\[\e[48;5;60m\]\[\e[38;5;255m\]"
	local USER_END="\[\e[0m\]\[\e[38;5;60m\]\[\e[48;5;67m\]\[\e[0m\]"

	local DIR="\[\e[0m\]\[\e[48;5;67m\]\[\e[38;5;255m\]"  
	local DIR_END="\[\e[0m\]\[\e[38;5;67m\]\[\e[48;5;236m\]\[\e[0m\]"

	local PROMPT="\[\e[0m\]\[\e[48;5;236m\]\[\e[38;5;255m\]"
	local PROMPT_END="\[\e[0m\]\[\e[38;5;236m\]\[\e[1m\]\[\e[0m\]"

	if [ ! -w "$PWD" ]; then
	# Current directory is not writable
	local DIR="\[\e[48;5;67m\]\[\e[38;5;255m\]" 
	local DIR_END="\[\e[0m\]\[\e[21m\]\[\e[48;5;60m\]\[\e[38;5;67m\]\[\e[0m\]\\[\e[38;5;15m\]\[\e[48;5;60m\]\[\e[1m\]    \[\e[0m\]\[\e[48;5;236m\]\[\e[38;5;60m\]\[\e[0m\]]"
	fi
		
	if [ "$PWD" == "$HOME" ]; then
		PS1="$USER    $USER_END$DIR    $DIR_END$PROMPT    $PROMPT_END "
	else
		PS1="$USER    $USER_END$DIR    \W  $DIR_END$PROMPT    $PROMPT_END "
	fi
	 
}

if [  "$TERM" != "linux" ]; then
	 PROMPT_COMMAND="ps1_powerline; $PROMPT_COMMAND"
fi


